package chapter3

/*
 * This Scala Testsuite was generated by the Gradle 'init' task.
 */

import org.junit.runner.RunWith
import org.scalatest.FunSuite
import org.scalatest.junit.JUnitRunner

@RunWith(classOf[JUnitRunner])
class Excercise2Suite extends FunSuite {

  test("tail") {
    assert(Excercise2.tail(Nil) == Nil)
    assert(Excercise2.tail(List(1)) == Nil)
    assert(Excercise2.tail(List(1, 2, 3)) == List(2, 3))
  }

}