package scala.chapter3
/*
 * This Scala Testsuite was generated by the Gradle 'init' task.
 */
import org.scalatest.FunSuite
import org.junit.runner.RunWith
import org.scalatest.junit.JUnitRunner

@RunWith(classOf[JUnitRunner])
class Excercise1Suite extends FunSuite {

  test("play around") {
      val x = Cons(1, Cons(2, Cons(3, Nil)))
      println(x)
      val y = List(1, 2, 3)
      println(y)

      val z = List(1, 2, 3) match {
          case Cons(_, t) => t
      }
      println(z)
  }

  test("test pattern matching") {
      val x = List(1, 2, 3, 4, 5) match {
          case Cons(x, Cons(2, Cons(4, _))) => x
          case Nil => 42
          case Cons(x, Cons(y, Cons(3, Cons(4, _)))) => x + y
          case _ => 101
      }

      assert(x == 3)
  }

}