/*
 * This Scala Testsuite was generated by the Gradle 'init' task.
 */
import org.scalatest.FunSuite
import org.junit.runner.RunWith
import org.scalatest.junit.JUnitRunner

@RunWith(classOf[JUnitRunner])
class Excercise4Suite extends FunSuite {
  test("curry") {
    val plus = Excercise4.curry((a: Int, b: Int) => a + b)
    val onePlus = plus(1)
    val threePlus = plus(3)
    assert(onePlus(2) == 3)
    assert(threePlus(-2) == 1)
  }

  test("uncurry") {
    val plus = Excercise4.uncurry((a: Int) => (b: Int) => a + b)
    assert(plus(1, 2) == 3)
  }

  test("compose") {
    val test = Excercise4.compose((a: Int) => a * 2, (s: String) => s.length())
    assert(test("alma") == 8)
  }
}
